#!/usr/bin/env python3
"""Bake an 8x16 bitmap font for the KELLER-OS GUI into Rust source.

The spec (GUI_SPECIFICATION.md §5) asks for a monospaced 8x16 bitmap font baked into the
binary as a constant byte array: 256 glyphs x 16 rows = 4096 bytes. Rasterising a scalable
font here, at build-authoring time, keeps the kernel free of any font engine.

Source face: Cascadia Mono (SIL Open Font License 1.1), which ships with Windows and is
redistributable. The generated table is a bitmap rendering, not the font file itself.

Usage:
    python dev-tools/make_font.py            # writes src/gui/font.rs
    python dev-tools/make_font.py --show A#  # print the rasterised glyphs as ASCII art
"""
import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

GLYPH_W = 8
GLYPH_H = 16
BASELINE = 12
CELLS = 256
DEFAULT_FONTS = [
    r"C:\Windows\Fonts\CascadiaMono.ttf",
    r"C:\Windows\Fonts\consola.ttf",
    r"/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
]
OUT = os.path.join("src", "gui", "font.rs")


def pick_font():
    for path in DEFAULT_FONTS:
        if os.path.exists(path):
            return path
    raise SystemExit("make_font: no monospaced face found; pass one via --font")


def fit_size(font_path):
    """Largest size whose advance is <= 8px and whose ascent+descent fits a 16px cell."""
    best = 8
    for size in range(8, 22):
        font = ImageFont.truetype(font_path, size)
        advance = font.getlength("M")
        ascent, descent = font.getmetrics()
        if advance <= GLYPH_W - 0.5 and ascent + descent <= GLYPH_H:
            best = size
    return best


def raster(font, code):
    image = Image.new("L", (GLYPH_W, GLYPH_H), 0)
    draw = ImageDraw.Draw(image)
    if code >= 32:
        draw.text((0, BASELINE), chr(code), font=font, fill=255, anchor="ls")
    rows = bytearray()
    for y in range(GLYPH_H):
        bits = 0
        for x in range(GLYPH_W):
            if image.getpixel((x, y)) >= 100:
                bits |= 1 << (7 - x)
        rows.append(bits)
    return bytes(rows)


def ascii_art(data):
    lines = []
    for y in range(GLYPH_H):
        row = data[y]
        lines.append("".join("#" if row & (1 << (7 - x)) else "." for x in range(GLYPH_W)))
    return lines


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default=None, help="path to a monospaced TTF/OTF")
    ap.add_argument("--show", default=None, help="print glyphs (e.g. 'A#' or 'AZ09')")
    args = ap.parse_args()

    font_path = args.font or pick_font()
    size = fit_size(font_path)
    font = ImageFont.truetype(font_path, size)

    if args.show:
        for ch in args.show:
            data = raster(font, ord(ch))
            print(f"--- {ch!r} (U+{ord(ch):04X}) ---")
            for line in ascii_art(data):
                print(line)
        return 0

    glyphs = [raster(font, code) for code in range(CELLS)]
    flat = b"".join(glyphs)
    assert len(flat) == CELLS * GLYPH_H

    face = os.path.basename(font_path)
    lines = []
    lines.append("//! 8x16 bitmap font for the GUI rasteriser: 256 glyphs x 16 rows = 4096 bytes.")
    lines.append("//!")
    lines.append(f"//! Generated by `dev-tools/make_font.py` from {face} (SIL Open Font License 1.1)")
    lines.append(f"//! at pixel size {size}, baseline row {BASELINE}. Regenerate with:")
    lines.append("//!")
    lines.append("//! ```text")
    lines.append("//! python dev-tools/make_font.py")
    lines.append("//! ```")
    lines.append("//!")
    lines.append("//! Row bits are MSB-first: bit 7 is the leftmost pixel of the 8-pixel cell. Every")
    lines.append("//! glyph is 16 bytes, so the table is indexable without any per-glyph metadata.")
    lines.append("")
    lines.append("/// Bytes per glyph (16 rows of 8 pixels).")
    lines.append("pub const GLYPH_BYTES: usize = 16;")
    lines.append("/// Glyph cell width in pixels.")
    lines.append("pub const GLYPH_WIDTH: usize = 8;")
    lines.append("/// Glyph cell height in pixels.")
    lines.append("pub const GLYPH_HEIGHT: usize = 16;")
    lines.append("/// Number of glyphs in the table (Latin-1 range, unrenderable codes stay blank).")
    lines.append("pub const GLYPH_COUNT: usize = 256;")
    lines.append("")
    lines.append("pub static FONT_8X16: [u8; GLYPH_COUNT * GLYPH_BYTES] = [")
    for code in range(CELLS):
        data = glyphs[code]
        row = "    " + " ".join(f"0x{byte:02x}," for byte in data)
        lines.append(f"{row} // {code:3d}")
    lines.append("];")
    lines.append("")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    print(f"make_font: wrote {OUT} ({os.path.getsize(OUT)} bytes, face {face} @ {size}px)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
